INSERT INTO producto (nombre_prod, descripcion_prod, precio_uni_prod, categoria_prod, peso_prod, ruta_prod)
VALUES
('Orgullo y prejuicio',
 'Orgullo y prejuicio, publicada por primera vez el 28 de enero de 1813 como una obra anónima, es la más famosa de las novelas de Jane Austen y una de las primeras comedias románticas en la historia de la novela.',
 35000.00,
 'Libros',
 0.45,
 'static/img/prod/orgullo_prejuicio.jfif'),

('Cien años de soledad',
 'Cien años de soledad, publicada en 1967, es la obra maestra del escritor colombiano Gabriel García Márquez. Narra la historia de la familia Buendía a lo largo de varias generaciones en el mítico pueblo de Macondo.',
 42000.00,
 'Libros',
 0.60,
 'static/img/prod/cien_anos_soledad.jpg'),

('Papas Margarita Limón',
 'Crujientes papas fritas con un toque ácido de limón, elaboradas con papas seleccionadas y fritas en aceite vegetal para ofrecer un sabor inconfundible. Perfectas para compartir o disfrutar como pasabocas en cualquier momento.',
 2500.00,
 'Snacks',
 0.05,
 'static/img/prod/papas_margarita_limon.png'),

('Las crónicas de Narnia',
 'Serie de novelas de fantasía de C. S. Lewis que narra las aventuras de varios niños en el mágico mundo de Narnia, lleno de criaturas míticas y lecciones sobre el bien y el mal.',
 48000.00,
 'Libros',
 0.75,
 'static/img/prod/cronicas_narnia.jpg'),

('Por un pedazo de tierra',
 'Obra que retrata la lucha, los sacrificios y la esperanza de campesinos que buscan justicia y un lugar propio en medio de los conflictos por la tierra.',
 32000.00,
 'Libros',
 0.52,
 'static/img/prod/por_un_pedazo_de_tierra.jpg'),

('Sentido y sensibilidad',
 'Clásico de Jane Austen que narra la vida de las hermanas Dashwood, entre la razón y el corazón en la Inglaterra del siglo XIX.',
 36000.00,
 'Libros',
 0.48,
 'static/img/prod/sentido_sensibilidad.jfif'),

('What on Earth Am I Here For?',
 'Versión en español de la obra de Rick Warren que invita a descubrir el propósito de la vida y el sentido espiritual de la existencia.',
 41000.00,
 'Libros',
 0.50,
 'static/img/prod/what_on_earth.png'),

('Holy Bible KL Version',
 'Edición en español de la Santa Biblia King James, ideal para la lectura diaria, estudio y reflexión espiritual personal o en grupo.',
 55000.00,
 'Libros',
 0.90,
 'static/img/prod/holy_bible.jfif'),

('El hombre en busca de sentido',
 'Obra de Viktor Frankl que relata su experiencia en los campos de concentración y su reflexión sobre la búsqueda de un propósito vital.',
 38000.00,
 'Libros',
 0.45,
 'static/img/prod/el_hombre_en_busca_de_sentido.jfif'),

('Vanish',
 'Thriller de Tess Gerritsen en el que la doctora Isles descubre un misterio ligado a una joven desaparecida y un oscuro secreto del pasado.',
 39000.00,
 'Libros',
 0.47,
 'static/img/prod/vanish_.jfif'),

('Bajo la misma estrella',
 'Novela de John Green sobre Hazel y Gus, dos jóvenes que enfrentan el cáncer con amor, humor y esperanza, recordando el valor de vivir plenamente.',
 74000.00,
 'Libros',
 0.48,
 'static/img/prod/Bajo_la_misma_estrella.jpeg'),

('The Amazing Spider-Man: Orígenes',
 'Cómic que muestra los inicios de Peter Parker como Spider-Man, su descubrimiento de los poderes y la responsabilidad de proteger a los demás.',
 60000.00,
 'Libros',
 0.35,
 'static/img/prod/Spiderman.jpg'),

('Superman: Hijo del mañana',
 'Cómic que sigue a Clark Kent en sus primeros años como Superman, descubriendo sus poderes y el deber de usar su fuerza para defender la justicia.',
 70000.00,
 'Libros',
 0.38,
 'static/img/prod/Superman.jpg'),

('Cornitos BBQ Dulce',
 'Crujientes nachos sabor BBQ dulce, elaborados con maíz natural y un toque de especias. Perfectos para compartir o disfrutar entre comidas.',
 2800.00,
 'Snacks',
 0.05,
 'static/img/prod/cornitos_pop.png'),

('Ferrero Rocher',
 'Delicioso bombón de avellana cubierto con chocolate y trozos de nuez, ideal para regalar o disfrutar como un postre elegante.',
 6500.00,
 'Snacks',
 0.04,
 'static/img/prod/ferrero_rocher.jfif'),

('Fidmi',
 'Galleta rellena de crema dulce, con una textura suave y crocante. Ideal para acompañar con café o como merienda rápida.',
 1500.00,
 'Snacks',
 0.03,
 'static/img/prod/fidmi.jfif'),

('Maní con sal La Especial',
 'Maní tostado con un toque de sal, fuente de energía y sabor. Perfecto para picar en cualquier momento del día.',
 2000.00,
 'Snacks',
 0.06,
 'static/img/prod/la_especial.webp'),

('Reese´s Puffs',
 'Cereal en forma de bolitas de mantequilla de maní y chocolate. Crujiente, dulce y con el sabor clásico de Reese’s en cada bocado.',
 5200.00,
 'Snacks',
 0.25,
 'static/img/prod/reeses_pop.jpg'),

('Choclitos Limón',
 'Crujientes palitos de maíz con sabor a limón, perfectos para disfrutar en reuniones o como snack refrescante.',
 1800.00,
 'Snacks',
 0.04,
 'static/img/prod/choclitos_limon.png'),

('Jet Wafer',
 'Galleta wafer rellena de crema y cubierta de chocolate Jet, una combinación perfecta de textura y sabor.',
 2200.00,
 'Snacks',
 0.03,
 'static/img/prod/jet_wafer.png'),

('Todo Rico BBQ',
 'Mezcla de snacks con sabor BBQ, ideal para compartir en fiestas o disfrutar viendo una película.',
 2500.00,
 'Snacks',
 0.05,
 'static/img/prod/todo_rico_bbq.png'),

('Chocoramo',
 'Bizcocho suave cubierto con una capa de delicioso chocolate, ideal para disfrutar en cualquier momento del día.',
 3000.00,
 'Snacks',
 0.06,
 'static/img/prod/chocoramo.png'),

('Maizitos',
 'Snacks de maíz con sabor tradicional, ligeros y crujientes, ideales para cualquier ocasión.',
 2700.00,
 'Snacks',
 0.05,
 'static/img/prod/maizitos.jpg'),

('Festival Fresa',
 'Galletas dulces rellenas de crema sabor fresa, perfectas para acompañar con leche o café en tus tardes.',
 1800.00,
 'Snacks',
 0.04,
 'static/img/prod/Festival_fresa.jpeg'),

('Reloj de Pulsera Clásico',
 'Reloj analógico con correa de cuero y caja metálica, elegante y cómodo para uso diario.',
 89000.00,
 'Accesorios',
 0.12,
 'static/img/prod/reloj_pulsera_clasico.jpg'),

('Gafas de Sol Polarizadas',
 'Gafas con protección UV400 y lentes polarizados que reducen el deslumbramiento y cuidan tu vista.',
 75000.00,
 'Accesorios',
 0.10,
 'static/img/prod/gafas_sol_polarizadas.jpg'),

('Cartera de Cuero',
 'Cartera de cuero genuino con múltiples compartimientos para billetes y tarjetas, práctica y elegante.',
 68000.00,
 'Accesorios',
 0.09,
 'static/img/prod/cartera_cuero.jpg'),

('Gorra Negra Casual',
 'Gorra ajustable de algodón con visera curva, ideal para protegerte del sol con estilo.',
 35000.00,
 'Accesorios',
 0.08,
 'static/img/prod/gorra_negra.jpg'),

('Audífonos Inalámbricos',
 'Audífonos Bluetooth con estuche de carga, sonido nítido y diseño ergonómico para uso prolongado.',
 99000.00,
 'Accesorios',
 0.07,
 'static/img/prod/audifonos_inalambricos.jpeg'),

('Cinturón de Cuero Café',
 'Cinturón elaborado en cuero legítimo con hebilla metálica, resistente y de diseño clásico.',
 56000.00,
 'Accesorios',
 0.15,
 'static/img/prod/cinturon_cuero_cafe.jpeg'),

('Mochila Urbana',
 'Mochila resistente al agua con compartimento para portátil y diseño moderno para uso diario.',
 125000.00,
 'Accesorios',
 0.85,
 'static/img/prod/mochila_urbana.jpeg'),

('Billetera Compacta',
 'Billetera delgada de cuero sintético con compartimentos para tarjetas y cierre seguro.',
 45000.00,
 'Accesorios',
 0.05,
 'static/img/prod/billetera_compacta.jpg'),

('Bufanda de Lana',
 'Bufanda suave y abrigada de lana, ideal para los días fríos con un toque elegante.',
 39000.00,
 'Accesorios',
 0.20,
 'static/img/prod/bufanda_lana.jpg'),

('Gorra Deportiva Blanca',
 'Gorra ligera y transpirable ideal para actividades al aire libre o entrenamiento físico.',
 33000.00,
 'Accesorios',
 0.07,
 'static/img/prod/gorra_deportiva_blanca.jpeg');

 INSERT INTO extra (nombre_extra, descripcion_extra,precio_extra, codigo_extra)
VALUES 
('Empaque de regalo', 'Decoración especial para obsequios', 5000, 'REGALO'),
('Entrega exprés', 'Entrega prioritaria en menos de 24 horas', 10000, 'EXPRESS'),
('Envío Seguro', 'Cobertura por pérdida o daño del paquete', 8000, 'SEGURO'),
('Manejo frágil', 'Protección especial para artículos delicados', 15000, 'FRAGIL');


INSERT INTO zona (nombre_zona, precio_zona) VALUES
('Bogotá', 8000),
('Medellín', 9000),      
('Bucaramanga', 12000),
('Cali', 10000),
('Barranquilla', 14000);
